import{S as v,a as S,i as l}from"./assets/vendor-DRgUjrIE.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const q=document.querySelector("#search-form"),m=document.querySelector(".gallery"),p=document.querySelector("#loader"),A=document.querySelector("#load-more"),g=document.querySelector(".button-container"),C="23458422-3da75be814240b3b99c5452e1",M="https://pixabay.com/api/",h=40;let i=1,d="",u=0;const E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(){p.classList.remove("loader-hidden")}function b(){p.classList.add("loader-hidden")}function P(){g.classList.remove("hidden")}function f(){g.classList.add("hidden")}function a(n,o="info"){const e={titleColor:"#fff",iconUrl:"./icon.svg",iconColor:"#fff",messageColor:"#fff",backgroundColor:"#ef4040",progressBarColor:"#b51b1b",message:n,position:"topRight",close:!0,timeout:5e3,onOpening:(c,t)=>{const r=t.querySelector(".iziToast-close");if(r){r.innerHTML="";const s=document.createElementNS("http://www.w3.org/2000/svg","svg");s.setAttribute("xmlns","http://www.w3.org/2000/svg"),s.setAttribute("width","20"),s.setAttribute("height","20"),s.setAttribute("viewBox","0 0 24 24"),s.setAttribute("fill","#fafafb"),s.innerHTML=`
          <path d="M18.3 5.71a1 1 0 0 0-1.41 0L12 10.59 7.11 5.7A1 1 0 0 0 5.7 7.11L10.59 12l-4.89 4.89a1 1 0 1 0 1.41 1.41L12 13.41l4.89 4.89a1 1 0 0 0 1.41-1.41L13.41 12l4.89-4.89a1 1 0 0 0 0-1.4z"/>
        `,s.style.cursor="pointer",r.appendChild(s)}}};o==="error"?l.error({...e,title:"Error"}):o==="warning"?l.warning({...e,title:"Warning"}):l.info({...e,title:"Info"})}async function w(n,o){const{data:e}=await S.get(M,{params:{key:C,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:o}});return e}function L(n){const o=n.map(e=>`
    <a href="${e.largeImageURL}" class="photo-card">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");m.insertAdjacentHTML("beforeend",o),E.refresh()}function I(){const{height:n}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}q.addEventListener("submit",async n=>{n.preventDefault();const o=n.target.searchQuery.value.trim();if(o){d=o,i=1,m.innerHTML="",f(),y();try{const e=await w(d,i);if(u=e.totalHits,e.hits.length===0){a("No images found for your query. Try something else!","warning");return}L(e.hits),u>h?P():f()}catch{a("Something went wrong while fetching data.","error")}finally{b()}}});A.addEventListener("click",async()=>{i++,y();try{const n=await w(d,i);L(n.hits),I();const o=Math.ceil(u/h);i>=o&&(f(),a("We're sorry, but you've reached the end of search results."))}catch{a("Could not load more images.","error")}finally{b()}});
//# sourceMappingURL=index.js.map
