import{S,a as q,i as l}from"./assets/vendor-DRgUjrIE.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function e(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=e(o);fetch(o.href,n)}})();const A=document.querySelector("#search-form"),m=document.querySelector(".gallery"),p=document.querySelector("#loader"),C=document.querySelector("#load-more"),g=document.querySelector(".button-container"),M="23458422-3da75be814240b3b99c5452e1",E="https://pixabay.com/api/",h=40;let i=1,d="",u=0;const P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(){p.classList.remove("loader-hidden")}function b(){p.classList.add("loader-hidden")}function w(){g.classList.remove("hidden")}function f(){g.classList.add("hidden")}function a(r,t="info"){const e={titleColor:"#fff",iconUrl:"./icon.svg",iconColor:"#fff",messageColor:"#fff",backgroundColor:"#ef4040",progressBarColor:"#b51b1b",message:r,position:"topRight",close:!0,timeout:5e3,onOpening:(c,o)=>{const n=o.querySelector(".iziToast-close");if(n){n.innerHTML="";const s=document.createElementNS("http://www.w3.org/2000/svg","svg");s.setAttribute("xmlns","http://www.w3.org/2000/svg"),s.setAttribute("width","20"),s.setAttribute("height","20"),s.setAttribute("viewBox","0 0 24 24"),s.setAttribute("fill","#fafafb"),s.innerHTML=`
          <path d="M18.3 5.71a1 1 0 0 0-1.41 0L12 10.59 7.11 5.7A1 1 0 0 0 5.7 7.11L10.59 12l-4.89 4.89a1 1 0 1 0 1.41 1.41L12 13.41l4.89 4.89a1 1 0 0 0 1.41-1.41L13.41 12l4.89-4.89a1 1 0 0 0 0-1.4z"/>
        `,s.style.cursor="pointer",n.appendChild(s)}}};t==="error"?l.error({...e,title:"Error"}):t==="warning"?l.warning({...e,title:"Warning"}):l.info({...e,title:"Info"})}async function L(r,t){const{data:e}=await q.get(E,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:t}});return e}function v(r){const t=r.map(e=>`
    <a href="${e.largeImageURL}" class="photo-card">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `).join("");m.insertAdjacentHTML("beforeend",t),P.refresh()}function I(){const r=document.querySelector(".gallery a");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}A.addEventListener("submit",async r=>{r.preventDefault();const t=r.target.searchQuery.value.trim();if(t){d=t,i=1,m.innerHTML="",f(),y();try{const e=await L(d,i);if(u=e.totalHits,e.hits.length===0){a("No images found for your query. Try something else!","warning");return}v(e.hits),u>h?w():f()}catch{a("Something went wrong while fetching data.","error")}finally{b()}}});C.addEventListener("click",async()=>{f(),i++,y();try{const r=await L(d,i);v(r.hits),I();const t=Math.ceil(u/h);i>=t?a("We're sorry, but you've reached the end of search results."):w()}catch{a("Could not load more images.","error")}finally{b()}});
//# sourceMappingURL=index.js.map
